[WIP] Push Transition
shaps80/SwiftUIBackports pull request #18
Opened 2022-08-10 11:52 UTC by drucelweisse

## Describe your changes

This pr adds new push [transition](https://developer.apple.com/documentation/swiftui/anytransition/push(from:)) from SwiftUI 4 lifecycle

- Added func push(from edge: Edge) -> AnyTransition

Question: Is there an example how to add it to Backport?

2022-08-11 09:14 UTC, shaps80 commented
@drucelweisse yep just checkout all existing backports. It's fairly self explanatory. We will need to test carefully to ensure it behaves identically to iOS 16 version (and other platforms) but the actual implementation you can workout from existing back ports

2022-08-11 18:27 UTC, drucelweisse commented
Yeah, I think that I got it, only current problem that AnyTransition doesn't have public init, and I'd like to use something like this: 

```swift
Text("some text").transition(.backport.push(from: .top))
```

Is it ok to use identity for backport value?

2022-08-12 09:44 UTC, shaps80 requested changes
Looking much nicer. What's left to do besides testing (I can do that)

2022-08-12 09:44 UTC, shaps80 commented on Sources/SwiftUIBackports/Shared/Transition/PushTransition.swift
> +
```suggestion
```

No top-level comments please

2022-08-12 09:44 UTC, shaps80 commented on Sources/SwiftUIBackports/Shared/Transition/PushTransition.swift
> +    static var backport: Backport<AnyTransition>{
```suggestion
    /// Wraps an `AnyTransition` that can be extended to provide backport functionality.
    static var backport: Backport<AnyTransition>{
```

2022-08-12 09:44 UTC, shaps80 commented on Sources/SwiftUIBackports/Shared/Transition/PushTransition.swift
> +    @available(macCatalyst, deprecated: 16.0)
I don't have macCatalyst support anywhere else to simplify, so this isn't required
```suggestion
```

2022-08-12 09:44 UTC, shaps80 commented on Sources/SwiftUIBackports/Shared/Transition/PushTransition.swift
> +
```suggestion
```

2022-08-12 09:44 UTC, shaps80 commented on Sources/SwiftUIBackports/Shared/Transition/PushTransition.swift
> +        return .asymmetric(insertion: .move(edge: edge), removal: .move(edge: oppositeEdge)).combined(with: .opacity)
```suggestion
        return .asymmetric(
            insertion: .move(edge: edge),
            removal: .move(edge: oppositeEdge)
        ).combined(with: .opacity)
```

2022-08-12 09:44 UTC, shaps80 commented on Sources/SwiftUIBackports/Shared/Transition/PushTransition.swift
> +        return .asymmetric(insertion: .move(edge: edge), removal: .move(edge: oppositeEdge)).combined(with: .opacity)
Just improves readability

2022-08-12 09:50 UTC, shaps80 commented
> Yeah, I think that I got it, only current problem that AnyTransition doesn't have public init, and I'd like to use something like this:
> 
> ```swift
> Text("some text").transition(.backport.push(from: .top))
> ```
> 
> Is it ok to use identity for backport value?

I think that's the right way to do it, as long as it behaves correctly I don't see an issue here.

2022-08-12 09:53 UTC, shaps80 commented on Sources/SwiftUIBackports/Shared/Transition/PushTransition.swift
> +public extension AnyTransition {
This should be in the `Backport.swift` file though

2022-08-12 18:21 UTC, drucelweisse commented
Currently I don't have an iOS 16 on my device nor Xcode 14, so I don't know how to test it correctly. You can checkout Kavsoft [video](https://youtu.be/e_2VCTr6uBk?t=73) as reference

2022-08-15 09:06 UTC, shaps80 commented
Ok got it! @drucelweisse amazing work thank you. I will check this out and just ensure it behaves correctly, then I'll get this included soon-ish. Thanks for your contribution 👍

2022-08-16 08:47 UTC, merged

2022-08-16 08:47 UTC, shaps80 commented
Merging as this looks great, I'll get it into the next release, thanks again!